Charts/Charts/Chart.cs
Hi,
I've moved the code in the setter of Series property to a new changed callback method attached to the Series dependency property.
This is needed because setter is not called when databinding is used.
Also, thanks for this nice project!
=> Fix support for databinding on Chart.Series

Charts/Charts/BarChart.cs, Charts/Charts/Chart.cs, Charts/Charts/LineChart.cs, Charts/Charts/PieChart.cs, Charts/Charts/RadarChart.cs, Charts/Charts/ScatterChart.cs, Charts/Charts/StackedBarChart.cs, Charts/LiveChartsCore.csproj, Charts/Properties/Settings.settings, Charts/Series/BarSerie.cs, Charts/Series/LineSerie.cs, Charts/Series/PieSerie.cs, Charts/Series/RadarSerie.cs, Charts/Series/ScatterSerie.cs, Charts/Series/Serie.cs, Charts/Series/StackedBarSerie.cs, Charts/TypeConverters/ValueCollectionConverter.cs, Charts/Viewers/Converters.cs, Charts/Viewers/PieSeriesViewer.xaml, Charts/Viewers/SerieConverter.cs, Charts/Viewers/SerieStandin.cs, Charts/Viewers/SeriesViewer.xaml, ChartsTest/MainWindow.xaml, ChartsTest/MainWindow.xaml.cs, ChartsTest/MoreExamples/LineAndAreaChart/Example1.xaml.cs, ChartsTest/MoreExamples/LineAndAreaChart/Example2.xaml.cs, WinForms/Form1.cs, WinForms/Properties/Settings.settings
I have successfully updated the library to support binding series now.  There have been a few other enhancements as well, mostly around not crashing when bindings haven't yet initialized.  Feel free to ask questions.
=> Updates for bindability

Charts/Charts/Chart.cs
Fixed the issue of accessing labels array with negative index
=> fixed access to labels array with negative index

LiveChartsCore/Series/PieSeries.cs
When disableanimation was set, the piechart would not be drawn
Added the second branch of the if, to display the graph
=> Fix for a bug -> disableanimation prevent drawing a piechart

LiveChartsCore/CoreComponents/Chart.cs, LiveChartsCore/Series/PieSeries.cs, WPFExamples/ExamplesMapper.cs, WPFExamples/z.DebugCases/101/Converter.cs
Closes #101 
this branch is just to solve 101 issue
=> Converters

LiveChartsCore/Series/LineSeries.cs, WPFExamples/BarExamples/MultiAxesBarChart/MultiAxChart.xaml, WPFExamples/BarExamples/MultiAxesBarChart/MultiAxChart.xaml.cs, WPFExamples/ExamplesMapper.cs, WPFExamples/MainWindow.xaml, WPFExamples/WPFExamples.csproj
Geting ready the final 0.6.6 details
=> 0.6.6 Preview

LiveChartsCore/Cache/AxisSeparationCache.cs, UnitTesting/UnitTesting.csproj, WPFExamples/z.DebugCases/101/ViewModel.cs
Reverts beto-rodriguez/Live-Charts#126
because I am having troubles to update portable branch.... I will this then
=> Revert "Fixed null exception on Application.Current"

Examples/Wpf/CartesianChart/PointShapeLine/PointShapeLineExample.cs, Examples/Wpf/CartesianChart/PointShapeLine/PointShapeLineExample.xaml, Examples/Wpf/MainWindow.xaml.cs, Examples/Wpf/Wpf.csproj, WpfView/Charts/Base/Chart.PublicMethods.cs, WpfView/Charts/Base/Chart.TooltipAndLegend.cs, WpfView/Components/Converters.cs, WpfView/DefaultGeometry.cs, WpfView/DefaultLegend.xaml, WpfView/DefaultTooltip.xaml, WpfView/DefaultTooltip.xaml.cs, WpfView/Points/HBezierPointView.cs, WpfView/Points/VBezierPointView.cs, WpfView/Series/LineSeries.cs, WpfView/Series/Series.cs, WpfView/WpfView.csproj
This changes the Line series points shape from Ellipse to arbitrary Path
shape with user defined geometry. If a Geometry is not defined, the
default Ellipse shape will be used instead.
=> Allows points to be a shape other than round. e.g.

.gitignore, Core/Core.nuspec, WinFormsView/WinFormsView.nuspec, WpfView/WpfView.nuspec, build.cake, build.ps1, tools/packages.config
=> Fixed nuspec definition to be inline with Nuget spesifcation

WpfView/Charts/Gauge.cs
With this Formula the GaugeControl also works with From Values other then 0
=> Fix for #233 Gauge Control Bugged

Core/core.docs, WpfView/Series/LineSeries.cs, WpfView/Series/StackedAreaSeries.cs, WpfView/Series/VerticalLineSeries.cs, WpfView/Series/VerticalStackedAreaSeries.cs, WpfView/wpf.docs
NOTE: Designer still doesn't draw series. Fixes #180
=> BUG FIX: #180 - Designer throws NullReferenceException

Core/Core.csproj, Core/SeriesAlgorithms/CandleAlgorithm.cs, Examples/Wpf/CartesianChart/Financial/CandleStickExample.xaml, Examples/Wpf/CartesianChart/Financial/CandleStickExample.xaml.cs, Examples/Wpf/CartesianChart/Financial/OhclExample.xaml, Examples/Wpf/CartesianChart/Financial/OhclExample.xaml.cs, Examples/Wpf/MainWindow.xaml.cs, Examples/Wpf/Wpf.csproj, WpfView/CandleSeries.cs, WpfView/Points/CandlePointView.cs, WpfView/WpfView.csproj
New Candle Series, thanks you very much @hulihutu9
=> Hulihutu9 master

WpfView/Charts/Base/Chart.cs
Changed condition from logical AND to logical OR.
Fixes #360
=> Fixed null reference in MapXAxes/MapYAxes, #360

Core/AxisCore.cs, Core/ChartPoint.cs, Core/Charting.cs, Core/Configurations/GanttMapper.cs, Core/Core.csproj, Core/Defaults/GanttPoint.cs, Core/SeriesAlgorithms/RowAlgorithm.cs, Examples/UWP/Commons/SampleDefinitions.cs, Examples/Uwp/CartesianChart/GanttChart/GanttExample.xaml, Examples/Uwp/CartesianChart/GanttChart/GanttExample.xaml.cs, Examples/Uwp/Uwp.csproj, Examples/WinForms/Cartesian/GanttChart/GanttExample.Designer.cs, Examples/WinForms/Cartesian/GanttChart/GanttExample.cs, Examples/WinForms/Cartesian/GanttChart/GanttExample.resx, Examples/WinForms/Main.Designer.cs, Examples/WinForms/Main.cs, Examples/WinForms/Winforms.csproj, Examples/Wpf/CartesianChart/GanttChart/GanttExample.xaml, Examples/Wpf/CartesianChart/GanttChart/GanttExample.xaml.cs, Examples/Wpf/MainWindow.xaml.cs, Examples/Wpf/Wpf.csproj, UwpView/RowSeries.cs, WpfView/RowSeries.cs, WpfView/VisualElement.cs
Welcome Gantt Chart 🎉 
*List the issues this PR solves, blank if none*
=> GanttChart

Examples/WinForms/Cartesian/GanttChart/GanttExample.cs, Examples/Wpf/CartesianChart/Missing Line Points/MissingPointsExample.xaml, Examples/Wpf/PieChart/PieChartExample.xaml, UwpView/Points/PiePointView.cs, WpfView/Points/PiePointView.cs
Fixes a bug where pie series was not placing labels correctly when it was not animated
#350
=> Fix pie labels issue

Core/Charts/ChartCore.cs, Core/Definitions/Points/IChartPointView.cs, WpfView/Points/HorizontalBezierPointView.cs, WpfView/Points/PointView.cs, WpfView/Points/VerticalBezierPointView.cs
=> fixes #381

Core/Charts/CartesianChartCore.cs
Added a check if VisualElements != null
#399
=> Checking VisualElements to avoid null reference, #399

Core40/BarLabelPosition.cs, Core40/Charts/ChartCore.cs, Core40/Definitions/Series/ISeriesView.cs, Core40/SeriesAlgorithms/HeatAlgorithm.cs, Core40/SeriesAlgorithms/LineAlgorithm.cs, Core40/SeriesAlgorithms/RowAlgorithm.cs, Examples/Uwp/CartesianChart/Linq/DataBase.cs, Examples/WinForms/Cartesian/Linq/DataBase.cs, Examples/Wpf/CartesianChart/Linq/DataBase.cs, UwpView/AxisSection.cs, WpfView/AxisSection.cs, WpfView/DefaultLegend.xaml.cs
Fixes many reported issues
All referenced issues
=> Fixing reported issues

Core/Charts/ChartCore.cs, Core/Properties/AssemblyInfo.cs, Core/SeriesAlgorithms/LineAlgorithm.cs, Core40/Charts/ChartCore.cs, Core40/Properties/AssemblyInfo.cs, Core40/SeriesAlgorithms/LineAlgorithm.cs, UwpView/LineSeries.cs, UwpView/Properties/AssemblyInfo.cs, WinFormsView/Properties/AssemblyInfo.cs, WpfView/LineSeries.cs, WpfView/Properties/AssemblyInfo.cs
More issues fixed, this PR closes 081 release
* Fixes an issue where starting a line series with double.Nan was not drawn correctly
* Updates assembly version to 0.8.1
* Fixes an issue with stackables series produced some commits ago.
=> 081 release

UwpView/Charts/Base/Chart.cs, WpfView/Charts/Base/Chart.cs
For more info see [#433](https://github.com/beto-rodriguez/Live-Charts/pull/433)
=> Rusanov vladimir master

WpfView/Charts/Base/Chart.cs
Clearing old axes before setting new ones
#432
=> Clearing old axes before setting new ones, #432

Core/ChartUpdater.cs, Core/Charts/CartesianChartCore.cs, Core/Configurations/Mappers.cs, Core/Definitions/Charts/IChartView.cs, Core/Properties/AssemblyInfo.cs, Core40/ChartUpdater.cs, Core40/Definitions/Charts/IChartView.cs, Core40/Properties/AssemblyInfo.cs, UnitTests/MemoryLeaks/DrawnShapes.cs, UnitTests/Other/SharedSeries.cs, UnitTests/SeriesAndValues/NullAndEmpty.cs, UnitTests/SeriesAndValues/SeriesAutoColors.cs, UwpView/Charts/Base/Chart.cs, UwpView/Properties/AssemblyInfo.cs, WinFormsView/Properties/AssemblyInfo.cs, WpfView/Charts/Base/Chart.cs, WpfView/Properties/AssemblyInfo.cs
fixed an issue where adding a new axis could throw an exception... updated assembly info
=> 092 release

Examples/Uwp/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml, Examples/Uwp/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml.cs, Examples/WinForms/Cartesian/Zooming and Panning/ZomingAndPanningExample.cs, Examples/Wpf/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml, Examples/Wpf/CartesianChart/ZoomingAndPanning/ZoomingAndPanning.xaml.cs, Examples/Wpf/Properties/Annotations.cs, UwpView/Axis.cs, UwpView/Series.cs
Not much, only updated zooming example to link it in the site
=> Zooming example update

UwpView/CandleSeries.cs, UwpView/ColumnSeries.cs, UwpView/HeatSeries.cs, UwpView/LineSeries.cs, UwpView/OhlcSeries.cs, UwpView/PieSeries.cs, UwpView/RowSeries.cs, UwpView/ScatterSeries.cs, UwpView/Series.cs, UwpView/StackedColumnSeries.cs, UwpView/StackedRowSeries.cs, UwpView/StepLineSeries.cs, UwpView/VerticalLineSeries.cs, WpfView/CandleSeries.cs, WpfView/ColumnSeries.cs, WpfView/HeatSeries.cs, WpfView/LineSeries.cs, WpfView/OhlcSeries.cs, WpfView/PieSeries.cs, WpfView/RowSeries.cs, WpfView/ScatterSeries.cs, WpfView/Series.cs, WpfView/StackedColumnSeries.cs, WpfView/StackedRowSeries.cs, WpfView/StepLineSeries.cs, WpfView/VerticalLineSeries.cs
=> complement to #471

LiveCharts.sln
there are using of  "LiveChartsTesterGuy" & "LiveChartsTesterWinForms", which is not in this repository.
remove these
=> remove non-existent project

WinFormsView/Gauge.cs, WpfView/Gauge.cs
Implemented DisableAnimations property to Gauge chart
Unable to render Gauge chart 'off-screen'
=> Implemented DisableAnimations property to Gauge

Core/Charts/CartesianChartCore.cs, Core40/Charts/CartesianChartCore.cs
Fixed a spelling mistake in an exception message.
#577
=> Fixed typo in error message
