LiveChartsCore/Series/LineSeries.cs

I got this exception while playing with the WPF demo project. Just found two things, first wrong removing ChartPoint from _primitiveDictionary and second the exception itself.
Just use the TryGetValue method and add some logging for the mistake, cause maybe the reason comes from other stuff.

Fix for KeyNotFoundException in Erase method of LineSeries

---

LiveChartsCore/CoreComponents/Chart.cs

Series is not null per construction, line in the ctor is
SetCurrentValue(SeriesProperty, new SeriesCollection(defaultConfig));
InitializeSeries was called once with empty Series. Then it was not called anymore when actual value was set.

minor fix, avoid early initialization state setting 

---

LiveChartsCore/Series/PieSeries.cs

When PieSeries.DataLabels=True, this allows the Chart.DataClick event to be fired when clicking on the label just like clicking on the pie slice.  It also prevents the slice animation from resetting when mousing over the label.

Forward mouse events from the pie slice text labels so they are not lost

---

LiveChartsCore/Cache/AxisSeparationCache.cs
UnitTesting/UnitTesting.csproj
WPFExamples/z.DebugCases/101/ViewModel.cs

When the method, "Remove", on the AxisSeparationCache class is called from a WinForms application, the Current Application is null. 
To fix this, I added a null check before invoking the method.
Since I'm using an old version of visual studio (2013), I needed to change the version of the unit tests .net framework so that the solution would be compatible with my environment.

Fixed null exception on Application.Current

---

WinFormsView/WinFormsView.nuspec
WpfView/WpfView.nuspec

Added LiveCharts as a dependency in the nuspec files for Winforms and WPF build.
It seems like the -IncludeReferencedProjects will only work when used with a .csproj file and not with a .nuspec file so I just added the dependency in the nuspec directly.

Include LiveCharts as dependency in Nuget build

---

WpfView/Points/ScatterPointView.cs

This is small modification with no actual effect since Width = Height = Diameter, but the inversion could trigger a bug later if the initializtion of Shape.Width/Height change

ScatterPointView: correctly set the shape position

---

Core/Helpers/NoisyCollection.cs

As per the issue referenced. Simply corrects the return value of int Add(object value) so that it matches the specification of IList
resolves #322

Correct the implementation of int Add(object value) - resolves #322

---

Core/ChartValues.cs

Enables it that users don't have to convert an existing IENumberable to a ChartValue, it accepts a IENumberable in the constructor. It might be more obvious to use it this way. It doesn't need the `using LiveCharts.Helpers` reference either.
Example:
Was:
```
double[] _values = new double[]{10, 20, 30, 40};
SeriesCollection = new SeriesCollection
{
new ColumnSeries
{
Title = "Example",
Values = _values.AsChartValues();
}
};
```
Becomes:
```
double[] _values = new double[]{10, 20, 30, 40};
SeriesCollection = new SeriesCollection
{
new ColumnSeries
{
Title = "Example",
Values = new ChartValues<double>(_values)
}
};
```
-

Initializes a new instance of chart values, with a given collection.

---

WpfView/Series.cs

Set default font for Series to Segoe UI to avoid binding error.
Fixes #363

Set default font for Series to Segoe UI, #363

---

UwpView/HeatSeries.cs
UwpView/UwpView.csproj
UwpView/UwpView.nuspec
UwpView/project.json
build.cake

Resolve NullReferenceException when DrawsHeatRange = false
Fixed up nuget packaging for UWP assemblies.
NullReferenceException in HeatSeries when DrawsHeatRange = false
'LiveCharts.Uwp.dll' not found when packaging UWP into nuget package

Resolve NullReferenceException when DrawsHeatRange = false

---

UwpView/HeatSeries.cs
UwpView/Points/HeatPoint.cs

I wanted a heat map that looked like Github's contribution chart. To do this I needed space around each of the data points. HeatSeries already exposed a Margin property so I simply copied this onto the Rectangle property of the HeatPoint and amended DrawOrMove to respect it.

Make HeatPoint respect HeatSeries.Margin

---

Core/SeriesAlgorithms/HeatAlgorithm.cs
UwpView/HeatSeries.cs
UwpView/Points/HeatPoint.cs

Bug fix and optimization for HeatAlgorithm
Fixed bug in ColorInterpolation where Red component was being interpolated from and to the same value.
Optimized InterpolateColorComponent by removing CorePoint allocations and adding short-circuit when interpolating between the same values.

HeatAlgorithm color interpolation

---

Core/BarLabelPosition.cs
UwpView/Points/ColumnPointView.cs
UwpView/Points/RowPointView.cs
UwpView/RowSeries.cs
UwpView/StackedColumnSeries.cs
UwpView/StackedRowSeries.cs
WpfView/Points/ColumnPointView.cs
WpfView/Points/RowPointView.cs
WpfView/RowSeries.cs
WpfView/StackedColumnSeries.cs
WpfView/StackedRowSeries.cs

Now we can specify the labels orientation in any bar series (Row, StackedRow, column and StackedColumn) 
Options are:
* Top 
* Parallel
* Perpendicular
* --Merged-- (Obsolete, replaced with Parallel) 
**Top**
**Parallel and merged**
**Perpendicular**
fixes #308

Allow labels rotation in bar series

---

Core/Definitions/Charts/IChartView.cs
Core/Events/Delegates.cs
Core40/Definitions/Charts/IChartView.cs
Core40/Events/Delegates.cs
UwpView/Charts/Base/Chart.cs
WpfView/Charts/Base/Chart.cs

Based on the DataClick event, the DataHover event allows users to add an event on DataMouseEnter. This can be useful for various interactivity features. The feature is written for WpfView and UwpView.

Add DataHover event based on DataClick event.

---

WpfView/Gauge.cs

Handles case when from, to and value are 0 in Gauge control.
fixes #420

fixe case when from, to and value are 0

---

UwpView/DefaultLegend.xaml.cs
UwpView/DefaultTooltip.xaml.cs
UwpView/IChartLegend.cs
UwpView/IChartTooltip.cs
UwpView/UwpView.csproj
WpfView/DefaultLegend.xaml.cs
WpfView/DefaultTooltip.xaml
WpfView/DefaultTooltip.xaml.cs
WpfView/IChartLegend.cs
WpfView/IChartTooltip.cs
WpfView/WpfView.csproj

DefualtTooltip got some design improvements, fixed some bugs, and it is now more flexible
This is the default look of it now
And you can now change drastically its look without the need of creating your own control:
```xml
<lvc:CartesianChart>
<lvc:CartesianChart.Resources>
<Style TargetType="lvc:DefaultTooltip">
<Setter Property="Background" Value="DarkOrange"></Setter>
<Setter Property="Foreground" Value="White"></Setter>
<Setter Property="ShowTitle" Value="False"></Setter>
<Setter Property="ShowSeries" Value="False"></Setter>
<Setter Property="FontSize" Value="16"></Setter>
<Setter Property="FontWeight" Value="Bold"></Setter>
<Setter Property="CornerRadius" Value="20"></Setter>
<Setter Property="Width" Value="40"></Setter>
<Setter Property="Height" Value="40"></Setter>
<Setter …
```

A Flexible default tooltip

---

WpfView/GeoMap.cs

* Copy&paste error in GeoMap.cs
* Fixed calculation of the color interpolation
#473

Fixed calculation of the color interpolation in WpfView/GeoMap.cs

---

WpfView/HeatSeries.cs

NullPointerException in case DrawsHeatRange = false
To Reproduce:
xaml:
```
<Window x:Class="WpfApplication1.MainWindow"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:local="clr-namespace:WpfApplication1"
xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
mc:Ignorable="d"
Title="MainWindow" Height="350" Width="525">
<Grid>
<DockPanel LastChildFill="True" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" >
<Button x:Name="AddStuff" Click="AddHeatMap">Press me</Button>
<lvc:CartesianChart LegendLocation="None" DisableAnimations="True"  x:Name="Chart" > …
```

Fixed NullPointerException in case DrawsHeatRange = false

---

WpfView/LineSeries.cs

Well, there was just a typo.
Renamed PointForeround to PointForeground.

Typo fix: PointForeround to PointForeground

---

Core/AxisCore.cs
Core/Charts/ChartCore.cs
Core/Defaults/AxisLimits.cs
Core40/Charts/ChartCore.cs
Core40/Defaults/AxisLimits.cs
Core40/WindowAxisCore.cs

Fix int overflow for large x values (e.g. DateTime.Ticks) #534
Fix int overflow for large x values (e.g. DateTime.Ticks) and remove one List<> allocation for an iterator instead. It would also help to add checked arithmetic setting to the project settings, but this is not included to this PR.
issue #534

Fix int overflow for large x values (e.g. DateTime.Ticks) #534

---

Core40/SeriesAlgorithms/CandleAlgorithm.cs
WpfView/Points/CandlePointView.cs

Changes solve the first two issues with issue #652 :
- Applies `FinancialColoringRules` even if animations are disabled
- Sends a reference to last point drawn to the point so that a candle can use the previous day's close compared to current to affect it's coloring
Does not solve the 3rd point: `GCandleSeries` is broken when trying to use `FinancialColoringRules`

652 financial coloring rules broken

---

WpfView/AxisSection.cs

Added call to `RemoveFromView` for `_label` as `RemoveFromDrawMargin` did not seem sufficient to remove the label
[648](https://github.com/beto-rodriguez/Live-Charts/issues/648)

648 axissection label not cleared

---

WpfView/PieSeries.cs
WpfView/StackedRowSeries.cs

Fixes bug #847.
Fill and Stroke are now displayed in StackedRowSeries.
Fixes bug #847.
I just copied the missing code from RowSeries.cs into StackedRowSeries.cs. I set up a test project, which worked. I used the Example PointState ([https://github.com/Live-Charts/Live-Charts/tree/master/Examples/Wpf/CartesianChart/PointState](url)) and changed RowSeries to StackedRowSeries in the xaml-File. It worked as expected.

Fixed bug fill and stroke of RowPointView in StackedRowSeries.cs
